'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRM_STAFF_LCN_BSN_EDIT_ADDR

    '''<summary>
    '''txt_bsn_citizen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bsn_citizen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_prefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_prefix As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_bsn_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bsn_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_bsn_lastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bsn_lastname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_HOUSENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_HOUSENO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_ENGADDR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_ENGADDR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_MOO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_MOO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_SOI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_SOI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_ROAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_ROAD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_Province control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Province As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_amphor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_amphor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_tambol As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_BSN_ZIPCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_ZIPCODE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_TELEPHONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_TELEPHONE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_FAX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_FAX As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_MOBILE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_MOBILE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_edit As Global.System.Web.UI.WebControls.Button
End Class
