'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRM_EXTEND_TIME_LOCATION_SAVE
    
    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbl_lcntpcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lcntpcd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_lcnno_display_full control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lcnno_display_full As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_thanm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_thanm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_thanm_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_thanm_address As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_grannm_lo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_grannm_lo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_thachngwtnm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_thachngwtnm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_expyear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_expyear As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_status_pay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_status_pay As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_staff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_staff As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_app_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_app_date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_cnsdcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_cnsdcd As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_confirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_confirm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_load0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_load0 As Global.System.Web.UI.WebControls.Button
End Class
