<?xml version="1.0" encoding="utf-8"?><Database Name="LGTCPN" Class="Linq_CPNDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=164.115.28.103;Initial Catalog=LGTCPN;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LGTCPNConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="fda.syslcnsid" Member="syslcnsids">
    <Type Name="syslcnsid">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="crtlct" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ntcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="taxno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="trdregno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ctzno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="idst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="phrno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nmprnst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cncdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lcnsidst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="scridst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="cncremark" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="otaxno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslcnsnm" Member="syslcnsnms">
    <Type Name="syslcnsnm">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lcnscd" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="prefixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="engnm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thalnm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="englnm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="suffixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lcnsst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="grplcnscd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="bsncd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="lcnsidst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="validdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="oldid" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslctaddr" Member="syslctaddrs">
    <Type Name="syslctaddr">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thaaddr" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="engaddr" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="room" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="mu" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="floor" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="thasoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="building" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="engsoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="tharoad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="engroad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="validdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="pvcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ttcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="branch" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslctnm" Member="syslctnms">
    <Type Name="syslctnm">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lctnmcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prefixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="engnm" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="suffixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lctst" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="tpnost" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ltntpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hptno" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="lcttpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctnmno" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dvcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="grplctnmcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thanmold" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="prefixcdold" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.sysusrid" Member="sysusrids">
    <Type Name="sysusrid">
      <Column Name="idcode" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lcnscd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usrlcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usrlcnscd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usrid" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="usrnm" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="usrst" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="dvcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="stfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="actcode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="appvdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="expdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="loginst" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="grpcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="refno" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ccdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ccremark" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[fda.sysaddrhn]" Member="fda_sysaddrhns">
    <Type Name="fda_sysaddrhn">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="houseno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.syschngwt" Member="syschngwts">
    <Type Name="syschngwt">
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thachngwtnm" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="engchngwtnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="thacwabbr" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="engcwabbr" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="mapgis" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="chngwtgrpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.sysamphr" Member="sysamphrs">
    <Type Name="sysamphr">
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thaamphrnm" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="engamphrnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="mapgis" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.systhmbl" Member="systhmbls">
    <Type Name="systhmbl">
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thmblcd" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thathmblnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="engthmblnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="mapgis" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRANSESSION_UPLOAD" Member="TRANSESSION_UPLOADs">
    <Type Name="TRANSESSION_UPLOAD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CITIEZEN_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIEZEN_ID_AUTHORIZE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPLOAD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REF_NO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DOWNLOAD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRANSESSION_DOWNLOAD" Member="TRANSESSION_DOWNLOADs">
    <Type Name="TRANSESSION_DOWNLOAD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CITIEZEN_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIEZEN_ID_AUTHORIZE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DOWNLOAD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYSTEM_NAME" Member="SYSTEM_NAMEs">
    <Type Name="SYSTEM_NAME">
      <Column Name="SYSTEM_ID" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="SYSTEM_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PROCESS_NAME" Member="PROCESS_NAMEs">
    <Type Name="PROCESS_NAME">
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="PROCESS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SYSTEM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>