'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POPUP_LCN_NCT_TEMP_INSERT

    '''<summary>
    '''lbl_main_lcnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_main_lcnno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_lcntpcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_lcntpcd As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_LCNNO_FORMAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LCNNO_FORMAT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_IDENTIFY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_IDENTIFY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_LICEN_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LICEN_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_IDENTIFY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_IDENTIFY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BSN_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BSN_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DRUG_GROUP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DRUG_GROUP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_LOCATION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LOCATION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_LOCATION_ADDR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LOCATION_ADDR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_TEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_TEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_LOCATION_KEEP_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LOCATION_KEEP_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_LOCATION_KRRP_ADDR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LOCATION_KRRP_ADDR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_KEEP_TEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_KEEP_TEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DATE_START control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DATE_START As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DATE_END control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DATE_END As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DATE_DAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DATE_DAY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DATE_MONTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DATE_MONTH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DATE_YEAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DATE_YEAR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_APPROVE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_APPROVE_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_APPROVE_POSITION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_APPROVE_POSITION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CONDITION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CONDITION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_NAME1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_NAME1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_NUMBER1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_NUMBER1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_NAME2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_NAME2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_NUMBER2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_NUMBER2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_NAME3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_NAME3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PHR_NUMBER3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PHR_NUMBER3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save As Global.System.Web.UI.WebControls.Button
End Class
