'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WS_DRUG_LOG_DR
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS_DRUGSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WS_DRUG
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private XML_DRUG_BC_UPDATE_TBOperationCompleted As System.Threading.SendOrPostCallback
        
        Private XML_DRUG_MERGE_UPDATEOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FDA_DRUG.My.MySettings.Default.FDA_DRUG_WS_DRUG_LOG_DR_WS_DRUG
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event XML_DRUG_BC_UPDATE_TBCompleted As XML_DRUG_BC_UPDATE_TBCompletedEventHandler
        
        '''<remarks/>
        Public Event XML_DRUG_MERGE_UPDATECompleted As XML_DRUG_MERGE_UPDATECompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_DRUG_BC_UPDATE_TB", RequestNamespace:="http://tempuri.org/", OneWay:=true, Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub XML_DRUG_BC_UPDATE_TB(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String)
            Me.Invoke("XML_DRUG_BC_UPDATE_TB", New Object() {Newcode, IDENTIFY_EDIT})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_BC_UPDATE_TBAsync(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String)
            Me.XML_DRUG_BC_UPDATE_TBAsync(Newcode, IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_BC_UPDATE_TBAsync(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.XML_DRUG_BC_UPDATE_TBOperationCompleted Is Nothing) Then
                Me.XML_DRUG_BC_UPDATE_TBOperationCompleted = AddressOf Me.OnXML_DRUG_BC_UPDATE_TBOperationCompleted
            End If
            Me.InvokeAsync("XML_DRUG_BC_UPDATE_TB", New Object() {Newcode, IDENTIFY_EDIT}, Me.XML_DRUG_BC_UPDATE_TBOperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_DRUG_BC_UPDATE_TBOperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_DRUG_BC_UPDATE_TBCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_DRUG_BC_UPDATE_TBCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_DRUG_MERGE_UPDATE", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function XML_DRUG_MERGE_UPDATE(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal identify_edit As String) As String
            Dim results() As Object = Me.Invoke("XML_DRUG_MERGE_UPDATE", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, identify_edit})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_MERGE_UPDATEAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal identify_edit As String)
            Me.XML_DRUG_MERGE_UPDATEAsync(pvncd, rgttpcd, drgtpcd, rgtno, identify_edit, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_MERGE_UPDATEAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal identify_edit As String, ByVal userState As Object)
            If (Me.XML_DRUG_MERGE_UPDATEOperationCompleted Is Nothing) Then
                Me.XML_DRUG_MERGE_UPDATEOperationCompleted = AddressOf Me.OnXML_DRUG_MERGE_UPDATEOperationCompleted
            End If
            Me.InvokeAsync("XML_DRUG_MERGE_UPDATE", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, identify_edit}, Me.XML_DRUG_MERGE_UPDATEOperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_DRUG_MERGE_UPDATEOperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_DRUG_MERGE_UPDATECompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_DRUG_MERGE_UPDATECompleted(Me, New XML_DRUG_MERGE_UPDATECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub XML_DRUG_BC_UPDATE_TBCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub XML_DRUG_MERGE_UPDATECompletedEventHandler(ByVal sender As Object, ByVal e As XML_DRUG_MERGE_UPDATECompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class XML_DRUG_MERGE_UPDATECompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
