'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_officer_format_maintain

    '''<summary>
    '''lb_Lifetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_Lifetime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_Month control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_Month As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_day control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_day As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_Storage_conditions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_Storage_conditions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_nature_medicine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_nature_medicine As Global.System.Web.UI.WebControls.Label
End Class
