<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_DRUG_IMPORT" Class="LINQ_FDA_DRUG_IMPORTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.132;Initial Catalog=FDA_DRUG_IMPORT;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_DRUG_IMPORTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_DETAIL" Member="FDA_DRUG_IMPORT_NYM_DETAILs">
    <Type Name="FDA_DRUG_IMPORT_NYM_DETAIL">
      <Column Name="NYM_DETAIL_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NYM_FK_IDA" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NYM_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_DETAILACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_SIZE" Member="FDA_DRUG_IMPORT_NYM_SIZEs">
    <Type Name="FDA_DRUG_IMPORT_NYM_SIZE">
      <Column Name="NYM_SIZE_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NYM_FK_IDA" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NYM_SIZE_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_SIZE_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_DETAILACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_UPLOAD" Member="FDA_DRUG_IMPORT_UPLOADs">
    <Type Name="FDA_DRUG_IMPORT_UPLOAD">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_DRUG_IMPORT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE_DRUG_IMPORT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PATH_FILE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE_FILE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NAME_FILE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATTACH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ATTACH_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATTACH_DES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_ATTACH_DOC" Member="M_ATTACH_DOCs">
    <Type Name="M_ATTACH_DOC">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ATTACH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ATTACH_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATTACH_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ATTACH_ADDDES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SET_COLOR" Member="SET_COLORs">
    <Type Name="SET_COLOR">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SYSTEM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SYSTEM_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="H_BG_COLOR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="H_HV_BG_COLOR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SET_PAGE_MAIN" Member="SET_PAGE_MAINs">
    <Type Name="SET_PAGE_MAIN">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SYSTEM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SYSTEM_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_WEIGHT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAGE_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAGE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAGE_PATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACTIVE_FACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SET_PAGE_SUB_MAIN" Member="SET_PAGE_SUB_MAINs">
    <Type Name="SET_PAGE_SUB_MAIN">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SYSTEM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SYSTEM_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_WEIGHT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAGE_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAGE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAGE_PATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACTIVE_FACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SET_PRIVILEGE" Member="SET_PRIVILEGEs">
    <Type Name="SET_PRIVILEGE">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_WEIGHT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SYSTEM_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SYSTEM_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_6_AFTER" Member="FDA_DRUG_IMPORT_NYM_6_AFTERs">
    <Type Name="FDA_DRUG_IMPORT_NYM_6_AFTER">
      <Column Name="NYM6_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_DATE_TOP_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM6_NAME_RECEIVE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TITLE_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_FULLNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_POSITION_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_NAME_OF_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_IMPORT_MED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_HEAL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_DISEASE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_COUNT_PERSON_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_NAME_DOC_MED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MEDICINE_NO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_BRANCH_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_HOSPITAL_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_NUMBER_AFTER" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_APLACE_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_CODE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_FOTMAT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_COUNT_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_MED_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_SERIES_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_DATE_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM6_MED_DATE_EXPICE_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_COUNTRY_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_COUNT_PAGE_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_DOC_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_NAME_ASK_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_TITLE_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_LICENSE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_BRANCH_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_HOSPITAL_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_CONTROL_MED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_IMPORTANT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_STRENGTH_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_IMPORT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_COUNTRY_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_PRODUCED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_IMPORT_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_TRADE_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ACTIVE_AFTER" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM6_COUNT_KEY_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_NEWCODE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITICEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_AFTER_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_5_AFTER" Member="FDA_DRUG_IMPORT_NYM_5_AFTERs">
    <Type Name="FDA_DRUG_IMPORT_NYM_5_AFTER">
      <Column Name="NYM5_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_DATE_TOP_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM5_NAME_RECEIVE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TITLE_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_FULLNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_POSITION_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NAME_OF_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_COUNT_UNIT_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_NAME_DOC_MED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MEDICINE_NO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_BRANCH_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_HOSPITAL_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NAME_PLACE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_NUMBER_AFTER" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_APLACE_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_CODE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_FOTMAT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_COUNT_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_MED_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_SERIES_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_DATE_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM5_MED_DATE_EXPICE_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_COUNTRY_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_OTHER_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NAME_ASK_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_TITLE_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_LICENSE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_BRANCH_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_HOSPITAL_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_IMPORTANT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_STRENGTH_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_IMPORT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_COUNTRY_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_PRODUCED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_IMPORT_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_TRADE_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ACTIVE_AFTER" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM5_COUNT_KEY_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_NEWCODE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOKEN_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITICEN_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_AFTER_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_1_DETAIL" Member="FDA_DRUG_IMPORT_NYM_1_DETAILs">
    <Type Name="FDA_DRUG_IMPORT_NYM_1_DETAIL">
      <Column Name="NYM1_DETAIL_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NYM1_DETAIL_FK_NYM1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NYM1_DETAIL_MED_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_DETAIL_ACINGREDIENTS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_DETAIL_PERUNIT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM1_DETAIL_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.STATUS_ALL_IMPORT" Member="STATUS_ALL_IMPORTs">
    <Type Name="STATUS_ALL_IMPORT">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STATUS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_GROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="READ_ONLY_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAL_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GROUP_DDL_SHOW" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_NAME_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SOP_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOG_STATUS_IMPORT" Member="LOG_STATUS_IMPORTs">
    <Type Name="LOG_STATUS_IMPORT">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_1" Member="FDA_DRUG_IMPORT_NYM_1s">
    <Type Name="FDA_DRUG_IMPORT_NYM_1">
      <Column Name="NYM1_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM1_DATE_TOP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM1_NAME_RECEIVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ALLOW_PLAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM1_WRITE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_WRITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM1_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM1_FULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ALLOW_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM1_ALLOW_NAME_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ALLOW_NAME_LICENSE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_LICENSE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_ADDRESS_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_RESERCH_NAME_TH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_RESERCH_NAME_EN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_RESERCH_CODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_RESERCH_ADDRESS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_MED_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_MED_FORMAT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_MED_NUMBER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM1_MED_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_NUMBER_PAGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM1_FINGERPRINT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_RCVNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM1_DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_BY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM1_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_3" Member="FDA_DRUG_IMPORT_NYM_3s">
    <Type Name="FDA_DRUG_IMPORT_NYM_3">
      <Column Name="NYM3_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM3_DATE_TOP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM3_NAME_RECEIVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ALLOW_PLAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_WRITE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_WRITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM3_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_FULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ALLOW_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_ALLOW_NAME_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_LICENSE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_WISH_MED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_COUNT_MED" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_DEPARTMAENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_DEPARTMAENT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_NAME_ASK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM3_DATE_TOP_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM3_NAME_RECEIVE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ALLOW_PLAN_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_WRITE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_WRITE_DATE_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM3_TITLE_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_FULLNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_FIRSTNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_LASTNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_POSITION_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ALLOW_NAME_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_ALLOW_NAME_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_LICENSE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ADDRESS_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_WISH_MED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_COUNT_MED_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM3_DEPARTMAENT_ID_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_DEPARTMAENT_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_NAME_ASK_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_ACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM3_COUNT_KEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_NEWCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_RCVNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM3_DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITICEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM3_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="APPROVE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ESTIMATE_CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EDIT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_5" Member="FDA_DRUG_IMPORT_NYM_5s">
    <Type Name="FDA_DRUG_IMPORT_NYM_5">
      <Column Name="NYM5_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_DATE_TOP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM5_NAME_RECEIVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_FULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NAME_OF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ADDRESS_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_COUNT_UNIT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_NAME_DOC_MED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MEDICINE_NO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_BRANCH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_HOSPITAL_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NAME_PLACE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_NUMBER" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_APLACE_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PLACE_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_CODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_FOTMAT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_COUNT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_MED_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_SERIES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_MED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM5_MED_DATE_EXPICE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_PRODUCTION_MED_COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_OTHER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_NAME_ASK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_LICENSE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_BRANCH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_HOSPITAL_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_IMPORTANT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_STRENGTH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_IMPORT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_PRODUCED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_TRADE_IMPORT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_INTENTION_TRADE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_ACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM5_COUNT_KEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_NEWCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_RCVNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM5_DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM5_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_4" Member="FDA_DRUG_IMPORT_NYM_4s">
    <Type Name="FDA_DRUG_IMPORT_NYM_4">
      <Column Name="NYM4_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM4_DATE_TOP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM4_NAME_RECEIVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ALLOW_PLAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_WRITE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_WRITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM4_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_FULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ALLOW_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_ALLOW_NAME_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_LICENSE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_WISH_MED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_COUNT_MED" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_DEPARTMAENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_DEPARTMAENT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_GIVETO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_NAME_ASK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM4_DATE_TOP_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM_NAME_RECEIVE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ALLOW_PLAN_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_WRITE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_WRITE_DATE_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM4_TITLE_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_FULLNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_FIRSTNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_LASTNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_POSITION_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ALLOW_NAME_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_ALLOW_NAME_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_LICENSE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ADDRESS_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_WISH_MED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_COUNT_MED_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM4_DEPARTMAENT_ID_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_DEPARTMAENT_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_GIVETO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_NAME_ASK_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_ACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM4_COUNT_KEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_NEWCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_RCVNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM4_DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM4_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="APPROVE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ESTIMATE_CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EDIT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_6" Member="FDA_DRUG_IMPORT_NYM_6s">
    <Type Name="FDA_DRUG_IMPORT_NYM_6">
      <Column Name="NYM6_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_DATE_TOP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM6_NAME_RECEIVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_FULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_NAME_OF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ADDRESS_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_IMPORT_MED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_HEAL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_DISEASE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_COUNT_PERSON" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_NAME_DOC_MED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MEDICINE_NO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_BRANCH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_HOSPITAL_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_NUMBER" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_APLACE_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PLACE_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_CODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_FOTMAT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_COUNT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_MED_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_SERIES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_MED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM6_MED_DATE_EXPICE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_PRODUCTION_MED_COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_COUNT_PAGE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_DOC_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_NAME_ASK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_LICENSE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_BRANCH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_HOSPITAL_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_CONTROL_MED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_IMPORTANT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_STRENGTH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_IMPORT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_PRODUCED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_TRADE_IMPORT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_INTENTION_TRADE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_ACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM6_COUNT_KEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_NEWCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_RCVNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM6_DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM6_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FDA_DRUG_IMPORT_NYM_2" Member="FDA_DRUG_IMPORT_NYM_2s">
    <Type Name="FDA_DRUG_IMPORT_NYM_2">
      <Column Name="NYM2_IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM2_DATE_TOP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM2_NAME_RECEIVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ALLOW_PLAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_WRITE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_WRITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM2_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_FULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ALLOW_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_ALLOW_NAME_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_LICENSE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_DISTRICT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_AMPHUR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_PROVINCE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_FAX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_WISH_MED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_COUNT_MED" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_DEPARTMAENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_DEPARTMAENT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_NAME_ASK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM2_DATE_TOP_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM2_NAME_RECEIVE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ALLOW_PLAN_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_WRITE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_WRITE_DATE_AFTER" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NYM2_TITLE_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_FULLNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_FIRSTNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_LASTNAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_POSITION_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ALLOW_NAME_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_ALLOW_NAME_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_LICENSE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_NO_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_SOI_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_STREET_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_MOO_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_DISTRICT_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_AMPHUR_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_PROVINCE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_PHONE_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_ADDRESS_FAX_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_WISH_MED_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_COUNT_MED_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NYM2_DEPARTMAENT_ID_AFTER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_DEPARTMAENT_NAME_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_NAME_ASK_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_DETAIL_AFTER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_ACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NYM2_COUNT_KEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_NEWCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_RCVNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NYM2_DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITICEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NYM2_IDENTIFY_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STAFF_RECEIVE_IDEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="APPROVE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ESTIMATE_CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EDIT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POSITION_CONSIDER_LINE5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>