<?xml version="1.0" encoding="utf-8"?><Database Name="LGT_NCT2" Class="Linq_NCTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=164.115.28.103;Initial Catalog=LGT_NCT2;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LGT_NCT2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MAS_NCT_LOCATION_TYPE" Member="MAS_NCT_LOCATION_TYPEs">
    <Type Name="MAS_NCT_LOCATION_TYPE">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NCT_LOCATION_TYPE_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NCT_LOCATION_TYPE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NCT_LOCATION_TYPE_GROUP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>