'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WS_Taxno_TaxnoAuthorize
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebService1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebService1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private insert_taxnoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insert_taxno_authorizeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProfile_byidentifyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insert_foreigner_syslcnsidOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insert_foreigner_syslcnsnmOperationCompleted As System.Threading.SendOrPostCallback
        
        Private update_ID_main_personOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDetail_Houseno_by_addressIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private update_taxnoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getData_By_Taxno_Form_Department_of_Local_administrationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FDA_DRUG.My.MySettings.Default.FDA_DRUG_WS_Taxno_TaxnoAuthorize_WebService1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event insert_taxnoCompleted As insert_taxnoCompletedEventHandler
        
        '''<remarks/>
        Public Event insert_taxno_authorizeCompleted As insert_taxno_authorizeCompletedEventHandler
        
        '''<remarks/>
        Public Event getProfile_byidentifyCompleted As getProfile_byidentifyCompletedEventHandler
        
        '''<remarks/>
        Public Event insert_foreigner_syslcnsidCompleted As insert_foreigner_syslcnsidCompletedEventHandler
        
        '''<remarks/>
        Public Event insert_foreigner_syslcnsnmCompleted As insert_foreigner_syslcnsnmCompletedEventHandler
        
        '''<remarks/>
        Public Event update_ID_main_personCompleted As update_ID_main_personCompletedEventHandler
        
        '''<remarks/>
        Public Event getDetail_Houseno_by_addressIDCompleted As getDetail_Houseno_by_addressIDCompletedEventHandler
        
        '''<remarks/>
        Public Event update_taxnoCompleted As update_taxnoCompletedEventHandler
        
        '''<remarks/>
        Public Event getData_By_Taxno_Form_Department_of_Local_administrationCompleted As getData_By_Taxno_Form_Department_of_Local_administrationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_taxno", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insert_taxno(ByVal _taxno As String) As String
            Dim results() As Object = Me.Invoke("insert_taxno", New Object() {_taxno})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insert_taxnoAsync(ByVal _taxno As String)
            Me.insert_taxnoAsync(_taxno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insert_taxnoAsync(ByVal _taxno As String, ByVal userState As Object)
            If (Me.insert_taxnoOperationCompleted Is Nothing) Then
                Me.insert_taxnoOperationCompleted = AddressOf Me.Oninsert_taxnoOperationCompleted
            End If
            Me.InvokeAsync("insert_taxno", New Object() {_taxno}, Me.insert_taxnoOperationCompleted, userState)
        End Sub
        
        Private Sub Oninsert_taxnoOperationCompleted(ByVal arg As Object)
            If (Not (Me.insert_taxnoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insert_taxnoCompleted(Me, New insert_taxnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_taxno_authorize", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insert_taxno_authorize(ByVal _taxno As String) As Boolean
            Dim results() As Object = Me.Invoke("insert_taxno_authorize", New Object() {_taxno})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insert_taxno_authorizeAsync(ByVal _taxno As String)
            Me.insert_taxno_authorizeAsync(_taxno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insert_taxno_authorizeAsync(ByVal _taxno As String, ByVal userState As Object)
            If (Me.insert_taxno_authorizeOperationCompleted Is Nothing) Then
                Me.insert_taxno_authorizeOperationCompleted = AddressOf Me.Oninsert_taxno_authorizeOperationCompleted
            End If
            Me.InvokeAsync("insert_taxno_authorize", New Object() {_taxno}, Me.insert_taxno_authorizeOperationCompleted, userState)
        End Sub
        
        Private Sub Oninsert_taxno_authorizeOperationCompleted(ByVal arg As Object)
            If (Not (Me.insert_taxno_authorizeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insert_taxno_authorizeCompleted(Me, New insert_taxno_authorizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getProfile_byidentify", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getProfile_byidentify(ByVal _identify As String) As Get_Profile
            Dim results() As Object = Me.Invoke("getProfile_byidentify", New Object() {_identify})
            Return CType(results(0),Get_Profile)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProfile_byidentifyAsync(ByVal _identify As String)
            Me.getProfile_byidentifyAsync(_identify, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProfile_byidentifyAsync(ByVal _identify As String, ByVal userState As Object)
            If (Me.getProfile_byidentifyOperationCompleted Is Nothing) Then
                Me.getProfile_byidentifyOperationCompleted = AddressOf Me.OngetProfile_byidentifyOperationCompleted
            End If
            Me.InvokeAsync("getProfile_byidentify", New Object() {_identify}, Me.getProfile_byidentifyOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProfile_byidentifyOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProfile_byidentifyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProfile_byidentifyCompleted(Me, New getProfile_byidentifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_foreigner_syslcnsid", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insert_foreigner_syslcnsid(ByVal lcnsid As Integer) As Boolean
            Dim results() As Object = Me.Invoke("insert_foreigner_syslcnsid", New Object() {lcnsid})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insert_foreigner_syslcnsidAsync(ByVal lcnsid As Integer)
            Me.insert_foreigner_syslcnsidAsync(lcnsid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insert_foreigner_syslcnsidAsync(ByVal lcnsid As Integer, ByVal userState As Object)
            If (Me.insert_foreigner_syslcnsidOperationCompleted Is Nothing) Then
                Me.insert_foreigner_syslcnsidOperationCompleted = AddressOf Me.Oninsert_foreigner_syslcnsidOperationCompleted
            End If
            Me.InvokeAsync("insert_foreigner_syslcnsid", New Object() {lcnsid}, Me.insert_foreigner_syslcnsidOperationCompleted, userState)
        End Sub
        
        Private Sub Oninsert_foreigner_syslcnsidOperationCompleted(ByVal arg As Object)
            If (Not (Me.insert_foreigner_syslcnsidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insert_foreigner_syslcnsidCompleted(Me, New insert_foreigner_syslcnsidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_foreigner_syslcnsnm", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insert_foreigner_syslcnsnm(ByVal bsncd As Integer) As Boolean
            Dim results() As Object = Me.Invoke("insert_foreigner_syslcnsnm", New Object() {bsncd})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insert_foreigner_syslcnsnmAsync(ByVal bsncd As Integer)
            Me.insert_foreigner_syslcnsnmAsync(bsncd, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insert_foreigner_syslcnsnmAsync(ByVal bsncd As Integer, ByVal userState As Object)
            If (Me.insert_foreigner_syslcnsnmOperationCompleted Is Nothing) Then
                Me.insert_foreigner_syslcnsnmOperationCompleted = AddressOf Me.Oninsert_foreigner_syslcnsnmOperationCompleted
            End If
            Me.InvokeAsync("insert_foreigner_syslcnsnm", New Object() {bsncd}, Me.insert_foreigner_syslcnsnmOperationCompleted, userState)
        End Sub
        
        Private Sub Oninsert_foreigner_syslcnsnmOperationCompleted(ByVal arg As Object)
            If (Not (Me.insert_foreigner_syslcnsnmCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insert_foreigner_syslcnsnmCompleted(Me, New insert_foreigner_syslcnsnmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_ID_main_person", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function update_ID_main_person(ByVal _taxno As String) As Object
            Dim results() As Object = Me.Invoke("update_ID_main_person", New Object() {_taxno})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub update_ID_main_personAsync(ByVal _taxno As String)
            Me.update_ID_main_personAsync(_taxno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub update_ID_main_personAsync(ByVal _taxno As String, ByVal userState As Object)
            If (Me.update_ID_main_personOperationCompleted Is Nothing) Then
                Me.update_ID_main_personOperationCompleted = AddressOf Me.Onupdate_ID_main_personOperationCompleted
            End If
            Me.InvokeAsync("update_ID_main_person", New Object() {_taxno}, Me.update_ID_main_personOperationCompleted, userState)
        End Sub
        
        Private Sub Onupdate_ID_main_personOperationCompleted(ByVal arg As Object)
            If (Not (Me.update_ID_main_personCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent update_ID_main_personCompleted(Me, New update_ID_main_personCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDetail_Houseno_by_addressID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDetail_Houseno_by_addressID(ByVal _houseno As String) As HOUSENO
            Dim results() As Object = Me.Invoke("getDetail_Houseno_by_addressID", New Object() {_houseno})
            Return CType(results(0),HOUSENO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDetail_Houseno_by_addressIDAsync(ByVal _houseno As String)
            Me.getDetail_Houseno_by_addressIDAsync(_houseno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDetail_Houseno_by_addressIDAsync(ByVal _houseno As String, ByVal userState As Object)
            If (Me.getDetail_Houseno_by_addressIDOperationCompleted Is Nothing) Then
                Me.getDetail_Houseno_by_addressIDOperationCompleted = AddressOf Me.OngetDetail_Houseno_by_addressIDOperationCompleted
            End If
            Me.InvokeAsync("getDetail_Houseno_by_addressID", New Object() {_houseno}, Me.getDetail_Houseno_by_addressIDOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDetail_Houseno_by_addressIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDetail_Houseno_by_addressIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDetail_Houseno_by_addressIDCompleted(Me, New getDetail_Houseno_by_addressIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_taxno", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub update_taxno(ByVal _taxno As String)
            Me.Invoke("update_taxno", New Object() {_taxno})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub update_taxnoAsync(ByVal _taxno As String)
            Me.update_taxnoAsync(_taxno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub update_taxnoAsync(ByVal _taxno As String, ByVal userState As Object)
            If (Me.update_taxnoOperationCompleted Is Nothing) Then
                Me.update_taxnoOperationCompleted = AddressOf Me.Onupdate_taxnoOperationCompleted
            End If
            Me.InvokeAsync("update_taxno", New Object() {_taxno}, Me.update_taxnoOperationCompleted, userState)
        End Sub
        
        Private Sub Onupdate_taxnoOperationCompleted(ByVal arg As Object)
            If (Not (Me.update_taxnoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent update_taxnoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getData_By_Taxno_Form_Department_of_Local_administration", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getData_By_Taxno_Form_Department_of_Local_administration(ByVal _taxno As String, ByRef ws_fields As root) As Object
            Dim results() As Object = Me.Invoke("getData_By_Taxno_Form_Department_of_Local_administration", New Object() {_taxno, ws_fields})
            ws_fields = CType(results(1),root)
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getData_By_Taxno_Form_Department_of_Local_administrationAsync(ByVal _taxno As String, ByVal ws_fields As root)
            Me.getData_By_Taxno_Form_Department_of_Local_administrationAsync(_taxno, ws_fields, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getData_By_Taxno_Form_Department_of_Local_administrationAsync(ByVal _taxno As String, ByVal ws_fields As root, ByVal userState As Object)
            If (Me.getData_By_Taxno_Form_Department_of_Local_administrationOperationCompleted Is Nothing) Then
                Me.getData_By_Taxno_Form_Department_of_Local_administrationOperationCompleted = AddressOf Me.OngetData_By_Taxno_Form_Department_of_Local_administrationOperationCompleted
            End If
            Me.InvokeAsync("getData_By_Taxno_Form_Department_of_Local_administration", New Object() {_taxno, ws_fields}, Me.getData_By_Taxno_Form_Department_of_Local_administrationOperationCompleted, userState)
        End Sub
        
        Private Sub OngetData_By_Taxno_Form_Department_of_Local_administrationOperationCompleted(ByVal arg As Object)
            If (Not (Me.getData_By_Taxno_Form_Department_of_Local_administrationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getData_By_Taxno_Form_Department_of_Local_administrationCompleted(Me, New getData_By_Taxno_Form_Department_of_Local_administrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Get_Profile
        
        Private sYSLCNSIDsField As syslcnsid
        
        Private sYSLCNSNMsField As syslcnsnm
        
        Private sYSLCTADDRsField As syslctaddr
        
        '''<remarks/>
        Public Property SYSLCNSIDs() As syslcnsid
            Get
                Return Me.sYSLCNSIDsField
            End Get
            Set
                Me.sYSLCNSIDsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SYSLCNSNMs() As syslcnsnm
            Get
                Return Me.sYSLCNSNMsField
            End Get
            Set
                Me.sYSLCNSNMsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SYSLCTADDRs() As syslctaddr
            Get
                Return Me.sYSLCTADDRsField
            End Get
            Set
                Me.sYSLCTADDRsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class syslcnsid
        
        Private iDAField As Integer
        
        Private identifyField As String
        
        Private lcnsidField As System.Nullable(Of Integer)
        
        Private crtlctField As System.Nullable(Of Short)
        
        Private birthdateField As System.Nullable(Of Date)
        
        Private chngwtcdField As System.Nullable(Of Short)
        
        Private ntcdField As System.Nullable(Of Short)
        
        Private taxnoField As String
        
        Private trdregnoField As String
        
        Private ctznoField As String
        
        Private remarkField As String
        
        Private idstField As System.Nullable(Of Short)
        
        Private phrnoField As String
        
        Private stfcdField As System.Nullable(Of Integer)
        
        Private nmprnstField As System.Nullable(Of Short)
        
        Private cncdateField As System.Nullable(Of Date)
        
        Private lstfcdField As System.Nullable(Of Integer)
        
        Private lcnsidstField As System.Nullable(Of Short)
        
        Private scridstField As System.Nullable(Of Short)
        
        Private lmdfdateField As System.Nullable(Of Date)
        
        Private urlField As String
        
        Private cncremarkField As String
        
        Private emailField As String
        
        Private otaxnoField As String
        
        Private typeField As System.Nullable(Of Integer)
        
        Private email_sroField As String
        
        Private email_contract_realField As String
        
        Private iD_mainField As String
        
        Private statusField As System.Nullable(Of Integer)
        
        Private person_status_IDField As System.Nullable(Of Integer)
        
        Private person_statusField As String
        
        Private sexField As String
        
        '''<remarks/>
        Public Property IDA() As Integer
            Get
                Return Me.iDAField
            End Get
            Set
                Me.iDAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property identify() As String
            Get
                Return Me.identifyField
            End Get
            Set
                Me.identifyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lcnsid() As System.Nullable(Of Integer)
            Get
                Return Me.lcnsidField
            End Get
            Set
                Me.lcnsidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property crtlct() As System.Nullable(Of Short)
            Get
                Return Me.crtlctField
            End Get
            Set
                Me.crtlctField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property birthdate() As System.Nullable(Of Date)
            Get
                Return Me.birthdateField
            End Get
            Set
                Me.birthdateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property chngwtcd() As System.Nullable(Of Short)
            Get
                Return Me.chngwtcdField
            End Get
            Set
                Me.chngwtcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ntcd() As System.Nullable(Of Short)
            Get
                Return Me.ntcdField
            End Get
            Set
                Me.ntcdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxno() As String
            Get
                Return Me.taxnoField
            End Get
            Set
                Me.taxnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property trdregno() As String
            Get
                Return Me.trdregnoField
            End Get
            Set
                Me.trdregnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ctzno() As String
            Get
                Return Me.ctznoField
            End Get
            Set
                Me.ctznoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property remark() As String
            Get
                Return Me.remarkField
            End Get
            Set
                Me.remarkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property idst() As System.Nullable(Of Short)
            Get
                Return Me.idstField
            End Get
            Set
                Me.idstField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property phrno() As String
            Get
                Return Me.phrnoField
            End Get
            Set
                Me.phrnoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property stfcd() As System.Nullable(Of Integer)
            Get
                Return Me.stfcdField
            End Get
            Set
                Me.stfcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property nmprnst() As System.Nullable(Of Short)
            Get
                Return Me.nmprnstField
            End Get
            Set
                Me.nmprnstField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property cncdate() As System.Nullable(Of Date)
            Get
                Return Me.cncdateField
            End Get
            Set
                Me.cncdateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lstfcd() As System.Nullable(Of Integer)
            Get
                Return Me.lstfcdField
            End Get
            Set
                Me.lstfcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lcnsidst() As System.Nullable(Of Short)
            Get
                Return Me.lcnsidstField
            End Get
            Set
                Me.lcnsidstField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property scridst() As System.Nullable(Of Short)
            Get
                Return Me.scridstField
            End Get
            Set
                Me.scridstField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lmdfdate() As System.Nullable(Of Date)
            Get
                Return Me.lmdfdateField
            End Get
            Set
                Me.lmdfdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cncremark() As String
            Get
                Return Me.cncremarkField
            End Get
            Set
                Me.cncremarkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property otaxno() As String
            Get
                Return Me.otaxnoField
            End Get
            Set
                Me.otaxnoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property type() As System.Nullable(Of Integer)
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property email_sro() As String
            Get
                Return Me.email_sroField
            End Get
            Set
                Me.email_sroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property email_contract_real() As String
            Get
                Return Me.email_contract_realField
            End Get
            Set
                Me.email_contract_realField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID_main() As String
            Get
                Return Me.iD_mainField
            End Get
            Set
                Me.iD_mainField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of Integer)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property person_status_ID() As System.Nullable(Of Integer)
            Get
                Return Me.person_status_IDField
            End Get
            Set
                Me.person_status_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property person_status() As String
            Get
                Return Me.person_statusField
            End Get
            Set
                Me.person_statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sex() As String
            Get
                Return Me.sexField
            End Get
            Set
                Me.sexField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class root
        
        Private citizenIDField As String
        
        Private nameEN_PrefixField As String
        
        Private nameEN_FirstNameField As String
        
        Private nameEN_MiddleNameField As String
        
        Private nameEN_SurNameField As String
        
        Private nameTH_PrefixField As String
        
        Private nameTH_FirstNameField As String
        
        Private nameTH_MiddleNameField As String
        
        Private nameTH_SurNameField As String
        
        Private sexIDField As Integer
        
        Private sexField As String
        
        Private birthDateField As String
        
        Private ageField As String
        
        Private personStatusIDField As Integer
        
        Private personStatusField As String
        
        Private addressIDField As String
        
        Private address_NoField As String
        
        Private address_MooField As String
        
        Private address_AlleyField As String
        
        Private address_SoiField As String
        
        Private address_RoadField As String
        
        Private address_TumbolField As String
        
        Private address_AmphurField As String
        
        Private address_ProvinceField As String
        
        Private issueDateField As String
        
        Private expireDateField As String
        
        Private issuerIDField As String
        
        Private issuerPlaceField As String
        
        Private issuerAgencyField As String
        
        Private nationalityField As String
        
        Private nationality_OldField As String
        
        Private nationality_ChangeDateField As String
        
        Private father_CitizenIDField As String
        
        Private father_NationalityField As String
        
        Private father_NameTH_FirstNameField As String
        
        Private father_FirstNameField As String
        
        Private mother_CitizenIDField As String
        
        Private mother_NationalityField As String
        
        Private mother_NameTH_FirstNameField As String
        
        Private mother_FirstNameField As String
        
        Private domicileTypeField As String
        
        Private domicileStatusField As String
        
        Private domicileDateField As String
        
        '''<remarks/>
        Public Property CitizenID() As String
            Get
                Return Me.citizenIDField
            End Get
            Set
                Me.citizenIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameEN_Prefix() As String
            Get
                Return Me.nameEN_PrefixField
            End Get
            Set
                Me.nameEN_PrefixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameEN_FirstName() As String
            Get
                Return Me.nameEN_FirstNameField
            End Get
            Set
                Me.nameEN_FirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameEN_MiddleName() As String
            Get
                Return Me.nameEN_MiddleNameField
            End Get
            Set
                Me.nameEN_MiddleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameEN_SurName() As String
            Get
                Return Me.nameEN_SurNameField
            End Get
            Set
                Me.nameEN_SurNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameTH_Prefix() As String
            Get
                Return Me.nameTH_PrefixField
            End Get
            Set
                Me.nameTH_PrefixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameTH_FirstName() As String
            Get
                Return Me.nameTH_FirstNameField
            End Get
            Set
                Me.nameTH_FirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameTH_MiddleName() As String
            Get
                Return Me.nameTH_MiddleNameField
            End Get
            Set
                Me.nameTH_MiddleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameTH_SurName() As String
            Get
                Return Me.nameTH_SurNameField
            End Get
            Set
                Me.nameTH_SurNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SexID() As Integer
            Get
                Return Me.sexIDField
            End Get
            Set
                Me.sexIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sex() As String
            Get
                Return Me.sexField
            End Get
            Set
                Me.sexField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BirthDate() As String
            Get
                Return Me.birthDateField
            End Get
            Set
                Me.birthDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Age() As String
            Get
                Return Me.ageField
            End Get
            Set
                Me.ageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonStatusID() As Integer
            Get
                Return Me.personStatusIDField
            End Get
            Set
                Me.personStatusIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonStatus() As String
            Get
                Return Me.personStatusField
            End Get
            Set
                Me.personStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddressID() As String
            Get
                Return Me.addressIDField
            End Get
            Set
                Me.addressIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_No() As String
            Get
                Return Me.address_NoField
            End Get
            Set
                Me.address_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Moo() As String
            Get
                Return Me.address_MooField
            End Get
            Set
                Me.address_MooField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Alley() As String
            Get
                Return Me.address_AlleyField
            End Get
            Set
                Me.address_AlleyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Soi() As String
            Get
                Return Me.address_SoiField
            End Get
            Set
                Me.address_SoiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Road() As String
            Get
                Return Me.address_RoadField
            End Get
            Set
                Me.address_RoadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Tumbol() As String
            Get
                Return Me.address_TumbolField
            End Get
            Set
                Me.address_TumbolField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Amphur() As String
            Get
                Return Me.address_AmphurField
            End Get
            Set
                Me.address_AmphurField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Province() As String
            Get
                Return Me.address_ProvinceField
            End Get
            Set
                Me.address_ProvinceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssueDate() As String
            Get
                Return Me.issueDateField
            End Get
            Set
                Me.issueDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpireDate() As String
            Get
                Return Me.expireDateField
            End Get
            Set
                Me.expireDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssuerID() As String
            Get
                Return Me.issuerIDField
            End Get
            Set
                Me.issuerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssuerPlace() As String
            Get
                Return Me.issuerPlaceField
            End Get
            Set
                Me.issuerPlaceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssuerAgency() As String
            Get
                Return Me.issuerAgencyField
            End Get
            Set
                Me.issuerAgencyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nationality() As String
            Get
                Return Me.nationalityField
            End Get
            Set
                Me.nationalityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nationality_Old() As String
            Get
                Return Me.nationality_OldField
            End Get
            Set
                Me.nationality_OldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nationality_ChangeDate() As String
            Get
                Return Me.nationality_ChangeDateField
            End Get
            Set
                Me.nationality_ChangeDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Father_CitizenID() As String
            Get
                Return Me.father_CitizenIDField
            End Get
            Set
                Me.father_CitizenIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Father_Nationality() As String
            Get
                Return Me.father_NationalityField
            End Get
            Set
                Me.father_NationalityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Father_NameTH_FirstName() As String
            Get
                Return Me.father_NameTH_FirstNameField
            End Get
            Set
                Me.father_NameTH_FirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Father_FirstName() As String
            Get
                Return Me.father_FirstNameField
            End Get
            Set
                Me.father_FirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mother_CitizenID() As String
            Get
                Return Me.mother_CitizenIDField
            End Get
            Set
                Me.mother_CitizenIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mother_Nationality() As String
            Get
                Return Me.mother_NationalityField
            End Get
            Set
                Me.mother_NationalityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mother_NameTH_FirstName() As String
            Get
                Return Me.mother_NameTH_FirstNameField
            End Get
            Set
                Me.mother_NameTH_FirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mother_FirstName() As String
            Get
                Return Me.mother_FirstNameField
            End Get
            Set
                Me.mother_FirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DomicileType() As String
            Get
                Return Me.domicileTypeField
            End Get
            Set
                Me.domicileTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DomicileStatus() As String
            Get
                Return Me.domicileStatusField
            End Get
            Set
                Me.domicileStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DomicileDate() As String
            Get
                Return Me.domicileDateField
            End Get
            Set
                Me.domicileDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HOUSENO
        
        Private addressIDField As String
        
        Private registryOfficeField As String
        
        Private address_NoField As String
        
        Private address_MooField As String
        
        Private address_AlleyField As String
        
        Private address_SoiField As String
        
        Private address_RoadField As String
        
        Private address_TumbolField As String
        
        Private address_AmphurField As String
        
        Private address_ProvinceField As String
        
        Private houseTypeField As String
        
        Private permitDateField As String
        
        Private disposeDateField As String
        
        Private villageNameField As String
        
        Private buildingNameField As String
        
        Private locationField As String
        
        Private postCodeField As String
        
        Private houseAttributeField As String
        
        Private houseSizeField As String
        
        Private houseVolumnField As String
        
        Private ownerFileField As String
        
        Private ownerFileIDField As String
        
        Private landSizeField As String
        
        Private tel01Field As String
        
        Private tel02Field As String
        
        Private tel03Field As String
        
        Private tel04Field As String
        
        Private tel05Field As String
        
        Private tel06Field As String
        
        Private tel07Field As String
        
        Private tel08Field As String
        
        Private tel09Field As String
        
        Private tel10Field As String
        
        Private approveIDField As String
        
        Private communityNameField As String
        
        '''<remarks/>
        Public Property AddressID() As String
            Get
                Return Me.addressIDField
            End Get
            Set
                Me.addressIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RegistryOffice() As String
            Get
                Return Me.registryOfficeField
            End Get
            Set
                Me.registryOfficeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_No() As String
            Get
                Return Me.address_NoField
            End Get
            Set
                Me.address_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Moo() As String
            Get
                Return Me.address_MooField
            End Get
            Set
                Me.address_MooField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Alley() As String
            Get
                Return Me.address_AlleyField
            End Get
            Set
                Me.address_AlleyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Soi() As String
            Get
                Return Me.address_SoiField
            End Get
            Set
                Me.address_SoiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Road() As String
            Get
                Return Me.address_RoadField
            End Get
            Set
                Me.address_RoadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Tumbol() As String
            Get
                Return Me.address_TumbolField
            End Get
            Set
                Me.address_TumbolField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Amphur() As String
            Get
                Return Me.address_AmphurField
            End Get
            Set
                Me.address_AmphurField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address_Province() As String
            Get
                Return Me.address_ProvinceField
            End Get
            Set
                Me.address_ProvinceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HouseType() As String
            Get
                Return Me.houseTypeField
            End Get
            Set
                Me.houseTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PermitDate() As String
            Get
                Return Me.permitDateField
            End Get
            Set
                Me.permitDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisposeDate() As String
            Get
                Return Me.disposeDateField
            End Get
            Set
                Me.disposeDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VillageName() As String
            Get
                Return Me.villageNameField
            End Get
            Set
                Me.villageNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BuildingName() As String
            Get
                Return Me.buildingNameField
            End Get
            Set
                Me.buildingNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostCode() As String
            Get
                Return Me.postCodeField
            End Get
            Set
                Me.postCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HouseAttribute() As String
            Get
                Return Me.houseAttributeField
            End Get
            Set
                Me.houseAttributeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HouseSize() As String
            Get
                Return Me.houseSizeField
            End Get
            Set
                Me.houseSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HouseVolumn() As String
            Get
                Return Me.houseVolumnField
            End Get
            Set
                Me.houseVolumnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OwnerFile() As String
            Get
                Return Me.ownerFileField
            End Get
            Set
                Me.ownerFileField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OwnerFileID() As String
            Get
                Return Me.ownerFileIDField
            End Get
            Set
                Me.ownerFileIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LandSize() As String
            Get
                Return Me.landSizeField
            End Get
            Set
                Me.landSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel01() As String
            Get
                Return Me.tel01Field
            End Get
            Set
                Me.tel01Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel02() As String
            Get
                Return Me.tel02Field
            End Get
            Set
                Me.tel02Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel03() As String
            Get
                Return Me.tel03Field
            End Get
            Set
                Me.tel03Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel04() As String
            Get
                Return Me.tel04Field
            End Get
            Set
                Me.tel04Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel05() As String
            Get
                Return Me.tel05Field
            End Get
            Set
                Me.tel05Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel06() As String
            Get
                Return Me.tel06Field
            End Get
            Set
                Me.tel06Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel07() As String
            Get
                Return Me.tel07Field
            End Get
            Set
                Me.tel07Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel08() As String
            Get
                Return Me.tel08Field
            End Get
            Set
                Me.tel08Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel09() As String
            Get
                Return Me.tel09Field
            End Get
            Set
                Me.tel09Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel10() As String
            Get
                Return Me.tel10Field
            End Get
            Set
                Me.tel10Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApproveID() As String
            Get
                Return Me.approveIDField
            End Get
            Set
                Me.approveIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CommunityName() As String
            Get
                Return Me.communityNameField
            End Get
            Set
                Me.communityNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class syslctaddr
        
        Private idField As Integer
        
        Private identifyField As String
        
        Private lcnsidField As System.Nullable(Of Integer)
        
        Private lctcdField As System.Nullable(Of Integer)
        
        Private thaaddrField As String
        
        Private engaddrField As String
        
        Private roomField As String
        
        Private muField As String
        
        Private floorField As String
        
        Private thasoiField As String
        
        Private buildingField As String
        
        Private engsoiField As String
        
        Private tharoadField As String
        
        Private engroadField As String
        
        Private thmblcdField As System.Nullable(Of Short)
        
        Private thmblnmField As String
        
        Private amphrcdField As System.Nullable(Of Short)
        
        Private amphrnmField As String
        
        Private chngwtcdField As System.Nullable(Of Short)
        
        Private chngwtnmField As String
        
        Private zipcodeField As System.Nullable(Of Integer)
        
        Private telField As String
        
        Private faxField As String
        
        Private validdateField As System.Nullable(Of Date)
        
        Private lstfcdField As System.Nullable(Of Integer)
        
        Private lmdfdateField As System.Nullable(Of Date)
        
        Private pvcodeField As System.Nullable(Of Short)
        
        Private amcodeField As System.Nullable(Of Short)
        
        Private ttcodeField As System.Nullable(Of Short)
        
        Private branchField As String
        
        Private fulladdrField As String
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property identify() As String
            Get
                Return Me.identifyField
            End Get
            Set
                Me.identifyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lcnsid() As System.Nullable(Of Integer)
            Get
                Return Me.lcnsidField
            End Get
            Set
                Me.lcnsidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lctcd() As System.Nullable(Of Integer)
            Get
                Return Me.lctcdField
            End Get
            Set
                Me.lctcdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property thaaddr() As String
            Get
                Return Me.thaaddrField
            End Get
            Set
                Me.thaaddrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property engaddr() As String
            Get
                Return Me.engaddrField
            End Get
            Set
                Me.engaddrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property room() As String
            Get
                Return Me.roomField
            End Get
            Set
                Me.roomField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mu() As String
            Get
                Return Me.muField
            End Get
            Set
                Me.muField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property floor() As String
            Get
                Return Me.floorField
            End Get
            Set
                Me.floorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property thasoi() As String
            Get
                Return Me.thasoiField
            End Get
            Set
                Me.thasoiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property building() As String
            Get
                Return Me.buildingField
            End Get
            Set
                Me.buildingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property engsoi() As String
            Get
                Return Me.engsoiField
            End Get
            Set
                Me.engsoiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tharoad() As String
            Get
                Return Me.tharoadField
            End Get
            Set
                Me.tharoadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property engroad() As String
            Get
                Return Me.engroadField
            End Get
            Set
                Me.engroadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property thmblcd() As System.Nullable(Of Short)
            Get
                Return Me.thmblcdField
            End Get
            Set
                Me.thmblcdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property thmblnm() As String
            Get
                Return Me.thmblnmField
            End Get
            Set
                Me.thmblnmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property amphrcd() As System.Nullable(Of Short)
            Get
                Return Me.amphrcdField
            End Get
            Set
                Me.amphrcdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property amphrnm() As String
            Get
                Return Me.amphrnmField
            End Get
            Set
                Me.amphrnmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property chngwtcd() As System.Nullable(Of Short)
            Get
                Return Me.chngwtcdField
            End Get
            Set
                Me.chngwtcdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property chngwtnm() As String
            Get
                Return Me.chngwtnmField
            End Get
            Set
                Me.chngwtnmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property zipcode() As System.Nullable(Of Integer)
            Get
                Return Me.zipcodeField
            End Get
            Set
                Me.zipcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tel() As String
            Get
                Return Me.telField
            End Get
            Set
                Me.telField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property validdate() As System.Nullable(Of Date)
            Get
                Return Me.validdateField
            End Get
            Set
                Me.validdateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lstfcd() As System.Nullable(Of Integer)
            Get
                Return Me.lstfcdField
            End Get
            Set
                Me.lstfcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lmdfdate() As System.Nullable(Of Date)
            Get
                Return Me.lmdfdateField
            End Get
            Set
                Me.lmdfdateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property pvcode() As System.Nullable(Of Short)
            Get
                Return Me.pvcodeField
            End Get
            Set
                Me.pvcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property amcode() As System.Nullable(Of Short)
            Get
                Return Me.amcodeField
            End Get
            Set
                Me.amcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ttcode() As System.Nullable(Of Short)
            Get
                Return Me.ttcodeField
            End Get
            Set
                Me.ttcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property branch() As String
            Get
                Return Me.branchField
            End Get
            Set
                Me.branchField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fulladdr() As String
            Get
                Return Me.fulladdrField
            End Get
            Set
                Me.fulladdrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class syslcnsnm
        
        Private idField As Integer
        
        Private identifyField As String
        
        Private lcnsidField As System.Nullable(Of Integer)
        
        Private lcnscdField As System.Nullable(Of Integer)
        
        Private prefixcdField As System.Nullable(Of Short)
        
        Private prefixcd2Field As System.Nullable(Of Short)
        
        Private prefixnmField As String
        
        Private prefixnm2Field As String
        
        Private thanmField As String
        
        Private engnmField As String
        
        Private lctcdField As System.Nullable(Of Integer)
        
        Private thalnmField As String
        
        Private englnmField As String
        
        Private suffixcdField As System.Nullable(Of Short)
        
        Private lcnsstField As System.Nullable(Of Short)
        
        Private grplcnscdField As System.Nullable(Of Short)
        
        Private bsncdField As System.Nullable(Of Integer)
        
        Private lstfcdField As System.Nullable(Of Integer)
        
        Private lmdfdateField As System.Nullable(Of Date)
        
        Private lcnsidstField As System.Nullable(Of Short)
        
        Private validdateField As System.Nullable(Of Date)
        
        Private oldidField As String
        
        Private typeField As System.Nullable(Of Integer)
        
        Private create_dateField As System.Nullable(Of Date)
        
        Private update_dateField As System.Nullable(Of Date)
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property identify() As String
            Get
                Return Me.identifyField
            End Get
            Set
                Me.identifyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lcnsid() As System.Nullable(Of Integer)
            Get
                Return Me.lcnsidField
            End Get
            Set
                Me.lcnsidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lcnscd() As System.Nullable(Of Integer)
            Get
                Return Me.lcnscdField
            End Get
            Set
                Me.lcnscdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property prefixcd() As System.Nullable(Of Short)
            Get
                Return Me.prefixcdField
            End Get
            Set
                Me.prefixcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property prefixcd2() As System.Nullable(Of Short)
            Get
                Return Me.prefixcd2Field
            End Get
            Set
                Me.prefixcd2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property prefixnm() As String
            Get
                Return Me.prefixnmField
            End Get
            Set
                Me.prefixnmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property prefixnm2() As String
            Get
                Return Me.prefixnm2Field
            End Get
            Set
                Me.prefixnm2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property thanm() As String
            Get
                Return Me.thanmField
            End Get
            Set
                Me.thanmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property engnm() As String
            Get
                Return Me.engnmField
            End Get
            Set
                Me.engnmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lctcd() As System.Nullable(Of Integer)
            Get
                Return Me.lctcdField
            End Get
            Set
                Me.lctcdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property thalnm() As String
            Get
                Return Me.thalnmField
            End Get
            Set
                Me.thalnmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property englnm() As String
            Get
                Return Me.englnmField
            End Get
            Set
                Me.englnmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property suffixcd() As System.Nullable(Of Short)
            Get
                Return Me.suffixcdField
            End Get
            Set
                Me.suffixcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lcnsst() As System.Nullable(Of Short)
            Get
                Return Me.lcnsstField
            End Get
            Set
                Me.lcnsstField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property grplcnscd() As System.Nullable(Of Short)
            Get
                Return Me.grplcnscdField
            End Get
            Set
                Me.grplcnscdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property bsncd() As System.Nullable(Of Integer)
            Get
                Return Me.bsncdField
            End Get
            Set
                Me.bsncdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lstfcd() As System.Nullable(Of Integer)
            Get
                Return Me.lstfcdField
            End Get
            Set
                Me.lstfcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lmdfdate() As System.Nullable(Of Date)
            Get
                Return Me.lmdfdateField
            End Get
            Set
                Me.lmdfdateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property lcnsidst() As System.Nullable(Of Short)
            Get
                Return Me.lcnsidstField
            End Get
            Set
                Me.lcnsidstField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property validdate() As System.Nullable(Of Date)
            Get
                Return Me.validdateField
            End Get
            Set
                Me.validdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property oldid() As String
            Get
                Return Me.oldidField
            End Get
            Set
                Me.oldidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property type() As System.Nullable(Of Integer)
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property create_date() As System.Nullable(Of Date)
            Get
                Return Me.create_dateField
            End Get
            Set
                Me.create_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property update_date() As System.Nullable(Of Date)
            Get
                Return Me.update_dateField
            End Get
            Set
                Me.update_dateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub insert_taxnoCompletedEventHandler(ByVal sender As Object, ByVal e As insert_taxnoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insert_taxnoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub insert_taxno_authorizeCompletedEventHandler(ByVal sender As Object, ByVal e As insert_taxno_authorizeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insert_taxno_authorizeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub getProfile_byidentifyCompletedEventHandler(ByVal sender As Object, ByVal e As getProfile_byidentifyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProfile_byidentifyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Get_Profile
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Get_Profile)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub insert_foreigner_syslcnsidCompletedEventHandler(ByVal sender As Object, ByVal e As insert_foreigner_syslcnsidCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insert_foreigner_syslcnsidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub insert_foreigner_syslcnsnmCompletedEventHandler(ByVal sender As Object, ByVal e As insert_foreigner_syslcnsnmCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insert_foreigner_syslcnsnmCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub update_ID_main_personCompletedEventHandler(ByVal sender As Object, ByVal e As update_ID_main_personCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class update_ID_main_personCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub getDetail_Houseno_by_addressIDCompletedEventHandler(ByVal sender As Object, ByVal e As getDetail_Houseno_by_addressIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDetail_Houseno_by_addressIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HOUSENO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HOUSENO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub update_taxnoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub getData_By_Taxno_Form_Department_of_Local_administrationCompletedEventHandler(ByVal sender As Object, ByVal e As getData_By_Taxno_Form_Department_of_Local_administrationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getData_By_Taxno_Form_Department_of_Local_administrationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ws_fields() As root
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),root)
            End Get
        End Property
    End Class
End Namespace
